### PR TITLE
ACF 11 and Lucee 5 compatibility. Load POI from class path first.

### PR DESCRIPTION
**Pull request by epfleckl**
While I know it's not a goal to be compatible with ACF 11, having lucee-spreadsheet work with both is really helpful before migrating large code bases from ACF to Lucee. Also, if the POI jars have already been added to the class path, there is no need to use JavaLoader.

### CODE REVIEW

**Comment by cfsimplicity** [comment]
Thanks for the PR, but I have a few comments/questions:

1) I see your point with ACF11/12 migration but I'm not sure it justifies the added burden of compatibility and having to run those platforms for testing which _official_ support would impose.

2) I'm happy to make minor post hoc tweaks though if that's all that's needed. No problem with the missing semi-colon on line 147 of tools.cfm and the alternate script syntax on 213/214 is OK, although I prefer the Lucee version personally.

3) I don't understand your change at lines 818/819. Why do you need to explicitly scope `headerRow`? And when using `local` you shouldn't need to declare the variable using `var`.

4) Could you explain the change to `package` access? Is that for ACF or the java path support?

5) I definitely like the idea of having the option to bypass JavaLoader in favour of POI in the class path. In Lucee 4 you need to customise your installation to do this as it ships with old POI jars that conflict if you don't remove them. I haven't used Lucee 5 yet but am hoping this will be easier - is that right?

6) But I think more code changes will be needed beyond the `loadPoi()` method. Have you run the test suite without JavaLoader? I would expect `read()` and `write()` to fail when using a password as the crypto functions require some specific functionality that it provides.

**Comment by epfleckl** [comment]
On May 14, 2016, at 5:17 AM, Julian Halliwell <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the PR, but I have a few comments/questions:

1) I see your point with ACF11/12 migration but I'm not sure it justifies the added burden of compatibility and having to run those platforms for testing which official support would impose.

I completely understand that compatibility with ACF is addition burden and not the goal of your project. For my purposes, I need to have it work with both ACF and Lucee until we can migrate away from ACF and use Lucee in production. That’s our goal in the next 6 months or so. Unfortunately, I have a large codebase with judicious use of cfspreadsheet, so there are a lot of code changes that need to be made. Personally, I prefer your implementation over cfspreadsheet and my near-term goal is to make it our standard moving forward. Rather than just modify the code locally, making future updates of lucee-spreadsheet difficult, so I thought I would pass the ACF changes along.


2) I'm happy to make minor post hoc tweaks though if that's all that's needed. No problem with the missing semi-colon on line 147 of tools.cfm and the alternate script syntax on 213/214 is OK, although I prefer the Lucee version personally.

I like the Lucee syntax as well, but ACF wasn’t having it. This is a perfect example of the added burden you mention, so I understand if you don’t want to do it.


3) I don't understand your change at lines 818/819. Why do you need to explicitly scope headerRow? And when using local you shouldn't need to declare the variable using var.

ACF complained (I’m a little surprised Lucee didn’t) that the variable “header” had already been declared. It’s declared on line 765 as an argument. The only change that was needed was to rename the variable but I thought explicitly scoping was preferable.


4) Could you explain the change to package access? Is that for ACF or the java path support?

Yes, in ACF, due to the includes for tools.cfm and formatting.cfm, Spreadsheet.cfc was not able to access their private methods. I’m not sure why this is different than Lucee, although I would tend to agree with the ACF logic (which is akin to including libraries in Java). Using package access allowed ACF to see the methods from Spreadsheet.cfc where it hadn’t previously, and it also provides the same level of protection as private when instantiating a Spreadsheet object.

NOTE: After I submitted my pull request, I ran into an error where ACF could not access methods in formatting.cfm. I had to change those methods to package access as well. If you accept the changes, I can submit a pull request for that as well.

5) I definitely like the idea of having the option to bypass JavaLoader in favour of POI in the class path. In Lucee 4 you need to customise your installation to do this as it ships with old POI jars that conflict if you don't remove them. I haven't used Lucee 5 yet but am hoping this will be easier - is that right?

Since I have time before migrating to Lucee in production, I’ve only been working with the Lucee 5 beta. I did not try Lucee 4. In Lucee 5, I just added your poi and xmlbeans jars to my <webroot>/WEB-INF/lucee/lib/ directory and restarted Lucee. With that, Lucee will use those jars and not need the JavaLoader. Now, that requires a server restart, but in production, that’s how we would implement it. If you’d like, I would be happy to test on Lucee 4.

Another reason to not use JavaLoader is decreased security. While Lucee did not complain, In CF11, I had to enable access to internal ColdFusion Java components for Javaloader to work.

6) But I think more code changes will be needed beyond the loadPoi() method. Have you run the test suite without JavaLoader? I would expect read() and write() to fail when using a password as the crypto functions require some specific functionality that it provides.

I haven’t run them. I have TestBox installed but am having trouble running the Spreadsheet tests (getting errors). I’m on a case-sensitive filesystem so let me look at that and run the tests.

Based on this, I think you should decline my pull request and I’ll issue another  to include the package scoping for formatting.cfm, case changes to the tests, and potentially removed or fixed bypassing of the JavaLoader.

**Comment by epfleckl** [comment]
JavaLoader is needed to correctly read and write and cannot be bypassed. Closing pull request and will resubmit when resolved and/or reverted. Thanks!

**Comment by cfsimplicity** [comment]
OK. I'm definitely keen on the option to bypass JL and will create a ticket for it. It is more complex than it seems though. Just adding the jars to the /lib folder isn't enough on Lucee 4. You must also remove the existing POI jars that ship with it, otherwise there will be confusion as to which should be used. JL is currently the only way of avoiding this manual customisation.

I will need to see whether the encrpytion can be done differently if using the class path.

Meantime, I'm happy to implement the compatibility changes you mention: the missing semi-colon and the script syntax for downloading.

The "headerRow" issue was a mistake on my part. I shouldn't have been using that variable name because as you say it was already being used as an argument. Lucee didn't break because it simply overwrote the previous variable (its local variable handling is better in my view). Thanks for that.

I am a bit puzzled by the "package" issue. I'd disagree that ACF's logic is right. Includes are just "fragments" rather than encapsulated elements of the "package", and including a file is really saying: "this code is part of the file, but I'm storing it separately for ease of management/re-use".

On reflection though, I've decided to do away with the includes since "mixing in" methods in this way is generally frowned upon. All the private methods are now part of the main Spreadsheet.cfc, which avoids all these issues while preserving the access semantics.

Thanks again for your input.

**Comment by cfsimplicity** [comment]
Hi Eric

I'm about to release a new version of the library which I'm hoping will address the Java loading issues we discussed last year. I've also done more work on ACF compatibility and made support for ACF11+ official.

Would you be able to quickly give the new version a run through to see if it works the way you were wanting? It's on the `develop` branch.

Have a look at [this guide to how the java loading should work](https://github.com/cfsimplicity/lucee-spreadsheet/wiki/Loading-the-POI-java-libraries) (and does according to my testing).

Any feedback gratefully received.
Julian.

**Pull request closed without merging**
