### PR TITLE
Add support for valid 6 character hexadecimal colors

### PR DESCRIPTION
**Pull request by JamoCA**
Most of my form color widgets and databases are configured to use hexadecimal 6 character color codes.  I updated the CFC to support HEX colors and auto-convert them to RGB and it works well.

_If you want to extend support to more color options, there's a ColdFusion [colorUtil](https://github.com/dbudde/colorUtil) CFC that provides additional hexadecimal/RBG-related functions._

### CODE REVIEW

**Comment by cfsimplicity** [comment]
Thanks. This pull request has been integrated manually.

**Comment by cfsimplicity** [comment]
James, I added a test, refactored it a bit and fixed an issue with handling hex values with a leading`#` sign.  Please check `develop` to make sure it's working for you.

**Comment by JamoCA** [comment]
It looks good.  I wonder if the `isHexColor` function should be updated to use regex to strip only a leading pound sign since that's the only place a hex color would be legally used.  (It may not be a big issue.)

_I like your use of `ToList()`.  I've been using Java's `ReplaceAll` instead of Adobe's `ReReplaceNoCase` function because it's succeeded where Adobe's built-in tag has thrown errors. After providing feedback on the bug, Adobe withdrawn it and flagged the behavior is "[as designed](https://tracker.adobe.com/#/view/CF-4165797)"._

**Comment by cfsimplicity** [comment]
I confess I didn't look closely at the `isHexColor` logic. Using regex is indeed simpler and avoids the need to strip pound signs twice. See https://github.com/cfsimplicity/lucee-spreadsheet/commit/aa8f14919b2fd9dcd46c8536c8d18adefee2d85c Thanks!

**Pull request closed without merging**
