### PR TITLE
Fix error in set cell value as type function

### PR DESCRIPTION
**Pull request by nelsonchuah**
Hi,

Got this error when trying to run setCellValueAsType() 
`Application Execution Exception
Error Type: java.lang.NoSuchMethodException : 0
Error Messages: No matching Method for setCellStyleProperty(org.apache.poi.hssf.usermodel.HSSFCell, string, numeric) found for org.apache.poi.ss.util.CellUtil`

Have updated the argument for the function, could you help review this fix?

Thank you
Nelson

### CODE REVIEW

**Comment by cfsimplicity** [comment]
Hi Nelson

`setCellValueAsType()` is a private method so can't be called directly from your code. Can you show the code you are using which is triggering this exception?

Can you also confirm which version of the library you are using and which version of POI (what are the names of the POI jars in the `/lib` folder)? 

The missing workbook argument to `setCellStyleProperty()` is not an error. That method signature was removed from the latest version of POI. See https://github.com/cfsimplicity/lucee-spreadsheet/issues/90

My guess is that you've upgraded to version 0.8.0 or later of the library cfc but haven't replaced the contents of the `/lib` folder that comes with it - which would trigger the exception you're getting. 

Julian.

**Comment by cfsimplicity** [comment]
Nelson, my previous comment wasn't quite right:

1) My guess about not updating POI can't be right. The library cfc would complain if the POI jars didn't match.

2) The `setCellStyleProperty` signature with the `workbook` argument hasn't yet been removed. It's still deprecated, but it now seems to be sheduled for removal in version 3.17 (during the beta it was marked for removal in 3.15 but they've apparently changed that with the final release). However, the signature I'm using ( `cell, propertyName, propertyValue` ) is what should be used now and in all my tests it does work.

Can you please show me the code and the values you are using which triggers the error?

**Comment by nelsonchuah** [comment]
Hi Julian,

Yup, my POI jar is at version 3.15. i have recently pull the latest master branch and got this error
Here is mine dump value and catch error 

lucee-spreadsheet error dump

Thank you 
Nelson

**Comment by cfsimplicity** [comment]
That error seems to be for the spreadsheet library embedded within Preside CMS. According to the master of that repo, they're using 0.5.11 of the library. Have you updated the version within Preside?

According to your error, the calling code in Preside is this:
```
spreadsheetLib.setCellValue( workbook, DateTimeFormat( submission.datecreated, "yyyy-mm-dd HH:nn:ss" ), row, 4 );
```
I've tested `setCellValue` in the latest master version using a date with the same format and there's no error. Can you please confirm that you have tried using the latest master *independently of Preside*?

**Comment by nelsonchuah** [comment]
Hi Julian,

Sorry for the late response, didn't have time to do the testing for this before.

Have now tested it and latest version of lucee-spreadsheet is working fine now. We can close and cancel this pull request, sorry for the trouble and thank you for the help :)

Thank you
Nelson

**Pull request closed without merging**
